import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiService } from '../lib/api';
import { Tag, ExternalLink, Loader2, GitCommit, Calendar, Rocket } from 'lucide-react';
import { formatDistanceToNow, format } from 'date-fns';
import toast from 'react-hot-toast';
import MarkdownPreview from '@uiw/react-markdown-preview';

interface ReleasesPageProps {
  repoId: string;
}

export const ReleasesPage: React.FC<ReleasesPageProps> = ({ repoId }) => {
  const queryClient = useQueryClient();

  const { data: releases, isLoading } = useQuery({
    queryKey: ['releases', repoId],
    queryFn: () => apiService.releases.listReleases(repoId),
  });

  const triggerReleaseMutation = useMutation({
    mutationFn: () => apiService.releases.triggerRelease(repoId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['releases', repoId] });
      toast.success('Release triggered successfully');
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.detail || 'Failed to trigger release');
    }
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 text-green-500 animate-spin" />
      </div>
    );
  }

  const getBumpBadge = (bumpType: string) => {
    switch (bumpType) {
      case 'major':
        return <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-red-500/10 text-red-400 border border-red-500/20">Major</span>;
      case 'minor':
        return <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-blue-500/10 text-blue-400 border border-blue-500/20">Minor</span>;
      case 'patch':
        return <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-green-500/10 text-green-400 border border-green-500/20">Patch</span>;
      default:
        return <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-gray-800 text-gray-400 border border-gray-700">{bumpType}</span>;
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center">
        <div>
          <h2 className="text-xl font-bold text-gray-100 flex items-center gap-2">
            <Tag className="w-6 h-6 text-green-400" />
            Releases History
          </h2>
          <p className="text-sm text-gray-500 mt-1">
            Track versions and changelogs generated by ContriBot.
          </p>
        </div>
        <button 
          onClick={() => triggerReleaseMutation.mutate()}
          disabled={triggerReleaseMutation.isPending}
          className="flex items-center gap-2 px-6 py-3 bg-green-500 hover:bg-green-400 text-gray-950 font-semibold rounded-lg transition-colors disabled:opacity-50"
        >
          {triggerReleaseMutation.isPending ? (
            <Loader2 className="w-5 h-5 animate-spin" />
          ) : (
            <Rocket className="w-5 h-5" />
          )}
          Trigger Release
        </button>
      </div>

      {releases?.length === 0 ? (
        <div className="text-center py-16 bg-gray-900/50 border border-gray-800 border-dashed rounded-xl">
          <Tag className="w-16 h-16 text-gray-600 mx-auto mb-4" />
          <h3 className="text-xl font-medium text-gray-300 mb-2">No releases yet</h3>
          <p className="text-gray-500 max-w-md mx-auto mb-8">
            Trigger a release to let ContriBot analyze your recent commits and generate a new version with a changelog.
          </p>
          <button 
            onClick={() => triggerReleaseMutation.mutate()}
            disabled={triggerReleaseMutation.isPending}
            className="px-6 py-3 bg-gray-800 hover:bg-gray-700 text-gray-200 font-semibold rounded-lg transition-colors border border-gray-700 disabled:opacity-50"
          >
            {triggerReleaseMutation.isPending ? 'Triggering...' : 'Create First Release'}
          </button>
        </div>
      ) : (
        <div className="relative border-l-2 border-gray-800 ml-6 space-y-12 pb-8">
          {releases?.map((release, index) => (
            <div key={release.id} className="relative pl-8">
              {/* Timeline dot */}
              <div className={`absolute -left-[11px] top-6 w-5 h-5 rounded-full border-4 border-gray-950 ${index === 0 ? 'bg-green-500' : 'bg-gray-600'}`} />
              
              <div className={`bg-gray-900 border ${index === 0 ? 'border-green-500/30 shadow-lg shadow-green-500/5' : 'border-gray-800'} rounded-xl overflow-hidden transition-all hover:border-gray-700`}>
                <div className="p-6 border-b border-gray-800 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                  <div className="flex items-center gap-4">
                    <h3 className="text-2xl font-bold text-gray-100 font-mono flex items-center gap-3">
                      {release.version}
                      {index === 0 && (
                        <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-green-500/20 text-green-400 border border-green-500/30 font-sans">
                          Latest
                        </span>
                      )}
                    </h3>
                    {getBumpBadge(release.bump_type || 'unknown')}
                  </div>
                  
                  <div className="flex items-center gap-4 text-sm text-gray-500">
                    <div className="flex items-center gap-1.5">
                      <Calendar className="w-4 h-4" />
                      {format(new Date(release.created_at), 'MMM d, yyyy')}
                    </div>
                    {release.github_release_url && (
                      <a 
                        href={release.github_release_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-1.5 text-blue-400 hover:text-blue-300 transition-colors"
                      >
                        <ExternalLink className="w-4 h-4" />
                        GitHub
                      </a>
                    )}
                  </div>
                </div>
                
                <div className="p-6 bg-gray-950/50">
                  {release.release_notes ? (
                    <div className="prose prose-invert max-w-none prose-pre:bg-gray-900 prose-pre:border prose-pre:border-gray-800">
                      <MarkdownPreview 
                        source={release.release_notes} 
                        style={{ backgroundColor: 'transparent', color: '#d1d5db' }}
                        wrapperElement={{
                          "data-color-mode": "dark"
                        }}
                      />
                    </div>
                  ) : (
                    <div className="text-gray-500 italic flex items-center gap-2">
                      <GitCommit className="w-4 h-4" />
                      No release notes available.
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
